// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_state.sql

package db

import (
	"context"
)

const CreateBotStatus = `-- name: CreateBotStatus :one
INSERT INTO "bot_state" (id, is_active, current_activity)
VALUES ($1, $2, $3)
RETURNING id, is_active, current_activity, created_at, updated_at
`

type CreateBotStatusParams struct {
	ID              string  `json:"id"`
	IsActive        bool    `json:"is_active"`
	CurrentActivity *string `json:"current_activity"`
}

func (q *Queries) CreateBotStatus(ctx context.Context, arg *CreateBotStatusParams) (*BotState, error) {
	row := q.db.QueryRow(ctx, CreateBotStatus, arg.ID, arg.IsActive, arg.CurrentActivity)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteBotStatus = `-- name: DeleteBotStatus :exec
DELETE FROM "bot_state" WHERE id = $1
`

func (q *Queries) DeleteBotStatus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteBotStatus, id)
	return err
}

const GetActiveBotStatus = `-- name: GetActiveBotStatus :one
SELECT id, is_active, current_activity, created_at, updated_at FROM "bot_state" WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveBotStatus(ctx context.Context) (*BotState, error) {
	row := q.db.QueryRow(ctx, GetActiveBotStatus)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetBotStatus = `-- name: GetBotStatus :one

SELECT id, is_active, current_activity, created_at, updated_at FROM "bot_state" WHERE id = $1
`

// Bot state queries
func (q *Queries) GetBotStatus(ctx context.Context, id string) (*BotState, error) {
	row := q.db.QueryRow(ctx, GetBotStatus, id)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListAllBotStatuses = `-- name: ListAllBotStatuses :many
SELECT id, is_active, current_activity, created_at, updated_at FROM "bot_state" ORDER BY created_at DESC
`

func (q *Queries) ListAllBotStatuses(ctx context.Context) ([]*BotState, error) {
	rows, err := q.db.Query(ctx, ListAllBotStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*BotState{}
	for rows.Next() {
		var i BotState
		if err := rows.Scan(
			&i.ID,
			&i.IsActive,
			&i.CurrentActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateBotActiveStatus = `-- name: UpdateBotActiveStatus :one
UPDATE "bot_state"
SET is_active = $2, "updated_at" = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, is_active, current_activity, created_at, updated_at
`

type UpdateBotActiveStatusParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateBotActiveStatus(ctx context.Context, arg *UpdateBotActiveStatusParams) (*BotState, error) {
	row := q.db.QueryRow(ctx, UpdateBotActiveStatus, arg.ID, arg.IsActive)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateBotActivity = `-- name: UpdateBotActivity :one
UPDATE "bot_state"
SET is_active = $2, "updated_at" = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, is_active, current_activity, created_at, updated_at
`

type UpdateBotActivityParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateBotActivity(ctx context.Context, arg *UpdateBotActivityParams) (*BotState, error) {
	row := q.db.QueryRow(ctx, UpdateBotActivity, arg.ID, arg.IsActive)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateBotStatus = `-- name: UpdateBotStatus :one
UPDATE "bot_state"
SET is_active = $2, "current_activity" = $3, "updated_at" = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, is_active, current_activity, created_at, updated_at
`

type UpdateBotStatusParams struct {
	ID              string  `json:"id"`
	IsActive        bool    `json:"is_active"`
	CurrentActivity *string `json:"current_activity"`
}

func (q *Queries) UpdateBotStatus(ctx context.Context, arg *UpdateBotStatusParams) (*BotState, error) {
	row := q.db.QueryRow(ctx, UpdateBotStatus, arg.ID, arg.IsActive, arg.CurrentActivity)
	var i BotState
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CurrentActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
