// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotState struct {
	ID              string             `json:"id"`
	IsActive        bool               `json:"is_active"`
	CurrentActivity *string            `json:"current_activity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Queue struct {
	ID              pgtype.UUID        `json:"id"`
	GuildID         string             `json:"guild_id"`
	TrackID         string             `json:"track_id"`
	UserID          *string            `json:"user_id"`
	UserName        *string            `json:"user_name"`
	CurrentPosition int32              `json:"current_position"`
	PlayNow         bool               `json:"play_now"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
}

type QueueHistory struct {
	ID       pgtype.UUID        `json:"id"`
	GuildID  string             `json:"guild_id"`
	TrackID  string             `json:"track_id"`
	UserID   *string            `json:"user_id"`
	UserName *string            `json:"user_name"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type Track struct {
	ID        pgtype.UUID        `json:"id"`
	Source    *string            `json:"source"`
	Url       *string            `json:"url"`
	Title     *string            `json:"title"`
	Artist    *string            `json:"artist"`
	Duration  *string            `json:"duration"`
	Thumnail  *string            `json:"thumnail"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
