// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_commands.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateCustomCommand = `-- name: CreateCustomCommand :one
INSERT INTO custom_commands (guild_id, name, response)
VALUES ($1, $2, $3)
RETURNING id, guild_id, name, response, created_at
`

type CreateCustomCommandParams struct {
	GuildID  string `json:"guild_id"`
	Name     string `json:"name"`
	Response string `json:"response"`
}

func (q *Queries) CreateCustomCommand(ctx context.Context, arg *CreateCustomCommandParams) (*CustomCommand, error) {
	row := q.db.QueryRow(ctx, CreateCustomCommand, arg.GuildID, arg.Name, arg.Response)
	var i CustomCommand
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Response,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteCustomCommand = `-- name: DeleteCustomCommand :exec
DELETE FROM custom_commands
WHERE guild_id = $1 AND id = $2
`

type DeleteCustomCommandParams struct {
	GuildID string      `json:"guild_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCustomCommand(ctx context.Context, arg *DeleteCustomCommandParams) error {
	_, err := q.db.Exec(ctx, DeleteCustomCommand, arg.GuildID, arg.ID)
	return err
}

const GetCustomCommandByName = `-- name: GetCustomCommandByName :one
SELECT id, guild_id, name, response, created_at
FROM custom_commands
WHERE guild_id = $1 AND lower(name) = lower($2)
LIMIT 1
`

type GetCustomCommandByNameParams struct {
	GuildID string `json:"guild_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetCustomCommandByName(ctx context.Context, arg *GetCustomCommandByNameParams) (*CustomCommand, error) {
	row := q.db.QueryRow(ctx, GetCustomCommandByName, arg.GuildID, arg.Name)
	var i CustomCommand
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Response,
		&i.CreatedAt,
	)
	return &i, err
}

const ListCustomCommands = `-- name: ListCustomCommands :many

SELECT id, guild_id, name, response, created_at
FROM custom_commands
WHERE guild_id = $1
ORDER BY lower(name) ASC
`

// Custom command queries
func (q *Queries) ListCustomCommands(ctx context.Context, guildID string) ([]*CustomCommand, error) {
	rows, err := q.db.Query(ctx, ListCustomCommands, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CustomCommand{}
	for rows.Next() {
		var i CustomCommand
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Response,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCustomCommand = `-- name: UpdateCustomCommand :one
UPDATE custom_commands
SET name = $3,
    response = $4
WHERE guild_id = $1
  AND id = $2
RETURNING id, guild_id, name, response, created_at
`

type UpdateCustomCommandParams struct {
	GuildID  string      `json:"guild_id"`
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Response string      `json:"response"`
}

func (q *Queries) UpdateCustomCommand(ctx context.Context, arg *UpdateCustomCommandParams) (*CustomCommand, error) {
	row := q.db.QueryRow(ctx, UpdateCustomCommand,
		arg.GuildID,
		arg.ID,
		arg.Name,
		arg.Response,
	)
	var i CustomCommand
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Response,
		&i.CreatedAt,
	)
	return &i, err
}
