// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_config.sql

package db

import (
	"context"
)

const GetWelcomeConfig = `-- name: GetWelcomeConfig :one
SELECT guild_id, welcome_channel_id, welcome_message
FROM guild_config
WHERE guild_id = $1
`

type GetWelcomeConfigRow struct {
	GuildID          string  `json:"guild_id"`
	WelcomeChannelID *string `json:"welcome_channel_id"`
	WelcomeMessage   *string `json:"welcome_message"`
}

func (q *Queries) GetWelcomeConfig(ctx context.Context, guildID string) (*GetWelcomeConfigRow, error) {
	row := q.db.QueryRow(ctx, GetWelcomeConfig, guildID)
	var i GetWelcomeConfigRow
	err := row.Scan(&i.GuildID, &i.WelcomeChannelID, &i.WelcomeMessage)
	return &i, err
}

const UpsertWelcomeConfig = `-- name: UpsertWelcomeConfig :one
INSERT INTO guild_config (guild_id, welcome_channel_id, welcome_message)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id) DO UPDATE
SET welcome_channel_id = EXCLUDED.welcome_channel_id,
    welcome_message = EXCLUDED.welcome_message,
    updated_at = now()
RETURNING guild_id, welcome_channel_id, welcome_message
`

type UpsertWelcomeConfigParams struct {
	GuildID          string  `json:"guild_id"`
	WelcomeChannelID *string `json:"welcome_channel_id"`
	WelcomeMessage   *string `json:"welcome_message"`
}

type UpsertWelcomeConfigRow struct {
	GuildID          string  `json:"guild_id"`
	WelcomeChannelID *string `json:"welcome_channel_id"`
	WelcomeMessage   *string `json:"welcome_message"`
}

func (q *Queries) UpsertWelcomeConfig(ctx context.Context, arg *UpsertWelcomeConfigParams) (*UpsertWelcomeConfigRow, error) {
	row := q.db.QueryRow(ctx, UpsertWelcomeConfig, arg.GuildID, arg.WelcomeChannelID, arg.WelcomeMessage)
	var i UpsertWelcomeConfigRow
	err := row.Scan(&i.GuildID, &i.WelcomeChannelID, &i.WelcomeMessage)
	return &i, err
}
