// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BotState struct {
	ID              string             `json:"id"`
	IsActive        bool               `json:"is_active"`
	CurrentActivity *string            `json:"current_activity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CustomCommand struct {
	ID        pgtype.UUID        `json:"id"`
	GuildID   string             `json:"guild_id"`
	Name      string             `json:"name"`
	Response  string             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GuildConfig struct {
	GuildID               string             `json:"guild_id"`
	DefaultVc             *string            `json:"default_vc"`
	Volume                int32              `json:"volume"`
	LanguageFilterEnabled bool               `json:"language_filter_enabled"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Queue struct {
	ID              pgtype.UUID        `json:"id"`
	GuildID         string             `json:"guild_id"`
	TrackID         pgtype.UUID        `json:"track_id"`
	UserID          *string            `json:"user_id"`
	UserName        *string            `json:"user_name"`
	CurrentPosition int32              `json:"current_position"`
	PlayNow         bool               `json:"play_now"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
}

type QueueHistory struct {
	ID       pgtype.UUID        `json:"id"`
	GuildID  string             `json:"guild_id"`
	TrackID  pgtype.UUID        `json:"track_id"`
	UserID   *string            `json:"user_id"`
	UserName *string            `json:"user_name"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type RecentlyPlayed struct {
	ID              pgtype.UUID        `json:"id"`
	GuildID         string             `json:"guild_id"`
	VoiceChannelID  string             `json:"voice_channel_id"`
	Url             string             `json:"url"`
	Title           *string            `json:"title"`
	Artist          *string            `json:"artist"`
	DurationSeconds int32              `json:"duration_seconds"`
	Thumbnail       *string            `json:"thumbnail"`
	AddedBy         *string            `json:"added_by"`
	AddedByID       *string            `json:"added_by_id"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
}

type Track struct {
	ID        pgtype.UUID        `json:"id"`
	Source    *string            `json:"source"`
	Url       *string            `json:"url"`
	Title     *string            `json:"title"`
	Artist    *string            `json:"artist"`
	Duration  *string            `json:"duration"`
	Thumnail  *string            `json:"thumnail"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserDiscordAccount struct {
	AppUserID     string    `json:"app_user_id"`
	DiscordUserID string    `json:"discord_user_id"`
	DisplayTag    string    `json:"display_tag"`
	AvatarHash    *string   `json:"avatar_hash"`
	LastSeenAt    time.Time `json:"last_seen_at"`
}
