// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateBotStatus(ctx context.Context, arg *CreateBotStatusParams) (*BotStatus, error)
	DeleteBotStatus(ctx context.Context, id string) error
	GetActiveBotStatus(ctx context.Context) (*BotStatus, error)
	// Bot status queries
	GetBotStatus(ctx context.Context, id string) (*BotStatus, error)
	ListAllBotStatuses(ctx context.Context) ([]*BotStatus, error)
	UpdateBotActiveStatus(ctx context.Context, arg *UpdateBotActiveStatusParams) (*BotStatus, error)
	UpdateBotActivity(ctx context.Context, arg *UpdateBotActivityParams) (*BotStatus, error)
	UpdateBotStatus(ctx context.Context, arg *UpdateBotStatusParams) (*BotStatus, error)
}

var _ Querier = (*Queries)(nil)
