// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateBotStatus(ctx context.Context, arg *CreateBotStatusParams) (*BotState, error)
	DeleteBotStatus(ctx context.Context, id string) error
	GetActiveBotStatus(ctx context.Context) (*BotState, error)
	// Bot state queries
	GetBotStatus(ctx context.Context, id string) (*BotState, error)
	GetDiscordIdentityByAppUserId(ctx context.Context, appUserID string) (*GetDiscordIdentityByAppUserIdRow, error)
	GetDiscordIdentityByDiscordUserId(ctx context.Context, discordUserID string) (*GetDiscordIdentityByDiscordUserIdRow, error)
	ListAllBotStatuses(ctx context.Context) ([]*BotState, error)
	UpdateBotActiveStatus(ctx context.Context, arg *UpdateBotActiveStatusParams) (*BotState, error)
	UpdateBotActivity(ctx context.Context, arg *UpdateBotActivityParams) (*BotState, error)
	UpdateBotStatus(ctx context.Context, arg *UpdateBotStatusParams) (*BotState, error)
	UpsertUserDiscordAccount(ctx context.Context, arg *UpsertUserDiscordAccountParams) error
}

var _ Querier = (*Queries)(nil)
