// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recently_played.sql

package db

import (
	"context"
)

const InsertRecentlyPlayed = `-- name: InsertRecentlyPlayed :exec
insert into recently_played (
    guild_id,
    voice_channel_id,
    url,
    title,
    artist,
    duration_seconds,
    thumbnail,
    added_by,
    added_by_id
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertRecentlyPlayedParams struct {
	GuildID         string  `json:"guild_id"`
	VoiceChannelID  string  `json:"voice_channel_id"`
	Url             string  `json:"url"`
	Title           *string `json:"title"`
	Artist          *string `json:"artist"`
	DurationSeconds int32   `json:"duration_seconds"`
	Thumbnail       *string `json:"thumbnail"`
	AddedBy         *string `json:"added_by"`
	AddedByID       *string `json:"added_by_id"`
}

func (q *Queries) InsertRecentlyPlayed(ctx context.Context, arg *InsertRecentlyPlayedParams) error {
	_, err := q.db.Exec(ctx, InsertRecentlyPlayed,
		arg.GuildID,
		arg.VoiceChannelID,
		arg.Url,
		arg.Title,
		arg.Artist,
		arg.DurationSeconds,
		arg.Thumbnail,
		arg.AddedBy,
		arg.AddedByID,
	)
	return err
}

const ListRecentlyPlayed = `-- name: ListRecentlyPlayed :many
select
    id,
    guild_id,
    voice_channel_id,
    url,
    title,
    artist,
    duration_seconds,
    thumbnail,
    added_by,
    added_by_id,
    added_at
from recently_played
where guild_id = $1
  and voice_channel_id = $2
order by added_at desc
limit $3
`

type ListRecentlyPlayedParams struct {
	GuildID        string `json:"guild_id"`
	VoiceChannelID string `json:"voice_channel_id"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListRecentlyPlayed(ctx context.Context, arg *ListRecentlyPlayedParams) ([]*RecentlyPlayed, error) {
	rows, err := q.db.Query(ctx, ListRecentlyPlayed, arg.GuildID, arg.VoiceChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecentlyPlayed{}
	for rows.Next() {
		var i RecentlyPlayed
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.VoiceChannelID,
			&i.Url,
			&i.Title,
			&i.Artist,
			&i.DurationSeconds,
			&i.Thumbnail,
			&i.AddedBy,
			&i.AddedByID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TrimRecentlyPlayed = `-- name: TrimRecentlyPlayed :exec
delete from recently_played
where id in (
    select rp.id
    from recently_played as rp
    where rp.guild_id = $1
      and rp.voice_channel_id = $2
    order by added_at desc
    offset $3
)
`

type TrimRecentlyPlayedParams struct {
	GuildID        string `json:"guild_id"`
	VoiceChannelID string `json:"voice_channel_id"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) TrimRecentlyPlayed(ctx context.Context, arg *TrimRecentlyPlayedParams) error {
	_, err := q.db.Exec(ctx, TrimRecentlyPlayed, arg.GuildID, arg.VoiceChannelID, arg.Offset)
	return err
}
